[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"
quilt_loader = "0.20.2"

quilted_fabric_api = "7.3.0+0.89.0-1.20.1"
emi = "1.0.20+1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.4.+" }
